name = "nada"
version = "0.1.0"
authors = [""]

[[programs]]
path = "src/main.py"
prime_size = 128


[[programs]]
path = "src/secret_addition.py"
name = "secret_addition"
prime_size = 128

[[programs]]
path = "src/financial_health_calculator.py"
name = "financial_health_calculator"
prime_size = 128
